### ISSUE TITLE
Weird Crash with MineFantasy Reforged

### ISSUE THREAD

**Issue by EmyLightsaber** [Darsenia/untouched_nature#1]
Forge Version: 14.23.5.2860
Minecraft Version: 1.12.2

When trying to make a pack just using MineFantasy Reforged, Untouched Nature, and a few others, it crashes right after 2/7 and trying to go into 3/7 on the loading screen with the following crash:

[crash-2023-01-23_16.16.12-client.txt](https://github.com/Darsenia/untouched_nature/files/10486271/crash-2023-01-23_16.16.12-client.txt)

**Comment by Darsenia** [comment]
The crash log doesn't say anything about UN directly, it's some MineFantasy mob spawning issue.Anyway, the biome dictionary part of the log is something that may be somehow connected with UN, I'l take a look.
Thanks for the feedback!

**Comment by Darsenia** [comment]
Unfortunately, my IDE cannot even run with MineFantasy installed (with any kind of mixins loader), and on the standalone client it also crashes (with the same error as yours), but it also says, that the MineFantasy  .jar file is corrupted and failed to read some it's class files.Turning off UN worldgen (there will be a plain vanilla world) doesn't help.It seems, that MineFantasy uses some advanced technics, that are not compatible with UN for unknown reason.
I can only recommend you to submit an issue to the MineFantasy author.
Here is the part of my crash report that is different from yours, if you 'll need it:
[latest.log](https://github.com/Darsenia/untouched_nature/files/10509724/latest.log)
